### PR TITLE
chore: sync with main branch

### PR DESCRIPTION
**Pull request by Zxilly**
prepare for https://github.com/casbin/casbin-editor/issues/73

@hsluoyz @nodece plz review

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Zxilly why make this PR and why make beta release? We already released v5.15.0 before your PR: https://github.com/casbin/node-casbin/releases/tag/v5.15.0

It's not reasonable to release v5.14.0-beta.4 after that.

**Comment by hsluoyz** [comment]
@Zxilly BTW, don't merge your own PR by yourself. We need to have a code review.

**Comment by Zxilly** [comment]
@hsluoyz `node-casbin beta` is platform independent, and `casbin-editor`  depends on that.
In fact, beta branch should be tagged as v6, maybe update later.
ref: https://github.com/casbin/node-casbin/issues/352

**Comment by hsluoyz** [comment]
@Zxilly as I said in: https://github.com/casbin/node-casbin/issues/352#issuecomment-1100198874 , it's not a good idea for current state to release v6.

**Pull request merged**
