### PR TITLE
refactor: reposition filter interface

### PR DESCRIPTION
**Pull request by Zxilly**
Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by nodece** [comment]
@Zxilly, @hsluoyz  This is inconsistent with the casbin implementation of go.

**Comment by hsluoyz** [comment]
@nodece which part is inconsistent?

**Comment by Zxilly** [comment]
@hsluoyz In casbin-golang, `removeFilteredPolicy` is in default `adapter`.

**Comment by hsluoyz** [comment]
We need to be consistent with Golang.

**Pull request merged**
