### PR TITLE
refactor: use synced Role Manager

### PR DESCRIPTION
**Pull request by Zxilly**
use `SyncedRoleManager` as a replacement of `RoleManager`

resolve: #292 

Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

### CODE REVIEW

**Comment by Zxilly** [comment]
This can be a breaking change, we need some discussion.

**Comment by Zxilly** [comment]
use await on sync function would be a grammar mistake. But if user manually judge the type of roleManger, they will meet type mistake like issue resolved by https://github.com/casbin/node-casbin/pull/297/commits/24f223771eedb4c700d54ba56d08fc490f33d88f.

**Comment by hsluoyz** [comment]
> This can be a breaking change, we need some discussion.

No breaking change is allowed.

**Comment by nodece** [comment]
@hsluoyz @Zxilly I think that use the `enforce` can meet most of the current needs, and there are too many changes to the API that provide synchronized versions.

**Comment by Zxilly** [comment]
Or we can make a sync version node-casbin?

**Comment by Zxilly** [comment]
@nodece I think we can use synced Role Manager when the user use synced Enforcer, but I didn't find a good way to check this when `initRmMap()` executed, do you have any idea?

**Comment by nodece** [comment]
@Zxilly I don't have any idea. At present, node-casbin does not have the necessary conditions to support synchronization method, so I don't merge this PR.

**Comment by hsluoyz** [comment]
No breaking change

**Comment by Zxilly** [comment]
@hsluoyz I have found a solution without breaking change.

**Pull request closed without merging**
