### PR TITLE
feat: changing TypeScript target from ES6 to ES2017

### PR DESCRIPTION
**Pull request by nodece**
Fix: https://github.com/casbin/node-casbin/issues/202

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### CODE REVIEW

**Comment by nodece** [comment]
@zhmushan  please take a look.

**Comment by zhmushan** [comment]
Why not use `ES2017`?

**Comment by nodece** [comment]
I think `ES2017` and `ESNext` have the same effect, so I use `ESNext` as the target.

**Review by zhmushan — APPROVED** [review]
LGTM

**Review by GopherJ — APPROVED** [review]

**Review by hsluoyz — APPROVED** [review]

**Pull request merged**
