### PR TITLE
Increase target version to ES2019

### PR DESCRIPTION
**Pull request by waitingsong**
1. Increase target version to ES2019
2. Add item pkg.engines.node with value ">=12.16.1"

### CODE REVIEW

**Review by zhmushan — CHANGES_REQUESTED** [review]
I do not agree with this change, it does not bring benefits, but it will cause compatibility issues

**Comment by waitingsong** [comment]
@zhmushan  The benifit is performance and also increase the  compatibility.

**Comment by waitingsong** [comment]
排查 Node.js 服务内存泄漏，没想到竟是它？
https://mp.weixin.qq.com/s/ZN3kmom9sIAi9HhrVWYl3Q

**Comment by nodece** [comment]
@waitingsong thanks for your contribution and I will comment after the test.

**Comment by hsluoyz** [comment]
@waitingsong also please use English as we are an international community, thanks!

**Comment by waitingsong** [comment]
> 
> 
> @waitingsong also please use English as we are an international community, thanks!

兄弟，上面那篇转载的文章全文中文，你把我引用的标题改为英文，不懂中文的照样看不懂的吧。

另，中文难道不是联合国法定语言，难道不是世界使用人数最多的语言（之一）吗？ 所谓国际性社区难道不能使用中文，不能为英文不那么流利的国人服务么。 是不是以后提issue也必须是英文，哪怕是处理中文xls文档出的问题？

**Comment by hsluoyz** [comment]
@waitingsong sorry for causing trouble for you. Like how UN defines its five working languages, we just defined English as our working language at GitHub (like the GitHub Web UI you saw) for serving the greater good. If you feel like another language, please join our QQ group here: https://casbin.org/en/help for better service.

**Comment by waitingsong** [comment]
如果你有尤雨溪那样的能力做出一款世界级软件，那么你有资格和底气干任何事情，比如拒绝提供中文文档，不接受中文issues，PR，甚至放弃中文用户。可是，在这之前，还是请先努力吧。
换个说法，如果有人在这儿（github）用德语发issue，PR，你是否还会如此“客气”呢？

当年只用MSN看不起用OICQ的假洋鬼子们（包括当年的我自己）醒醒吧，这世界改变了。

**Pull request closed without merging**
