### PR TITLE
Fix deleteUser and improve RBAC test coverage

### PR DESCRIPTION
**Pull request by Sefriol**
Tasks:
- [x] Improve RBAC test coverage
- [x] fix deleteUser

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Sefriol please fix CI error.

**Comment by nodece** [comment]
@Sefriol lgtm. Can you fix the deleteUser API?

**Comment by Sefriol** [comment]
I'll fix that later today!

**Comment by hsluoyz** [comment]
Fix: https://github.com/casbin/node-casbin/issues/118

**Pull request merged**
