### PR TITLE
feat: add @casbin/core package

### PR DESCRIPTION
**Pull request by nodece**
### Summary

Extract a common package from the `node-casbin`, and named `@casbin/core`, it doesn't use the any Node.js feature, can be used to all JavaScript platform.

**Note:** This package is not fully compatible with `node-casbin`.

### Background

#257, #270 

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### CODE REVIEW

**Comment by Zxilly** [comment]
@nodece Maybe we should work on another branch, like `dev`?

**Comment by nodece** [comment]
@Zxilly Using master and dev is the same for current development mode.

**Review by Zxilly — APPROVED** [review]
Maybe `core` but not `casbin-core` will be much better. `@casbin/core` means a package named `core` under org casbin

**Comment by harveyappleton** [comment]
@hsluoyz how come this PR was closed?

**Comment by Zxilly** [comment]
@harveyappleton We are working on the https://github.com/casbin/casbin.js/tree/v1

**Comment by harveyappleton** [comment]
Ah awesome! Thanks guys!

**Pull request closed without merging**
