### PR TITLE
chore: use monorep

### PR DESCRIPTION
**Pull request by nodece**
This PR is for the next step to extract the public package preparation. 

### Changes

- disable the semantic-release because it does not support monorepo
- use yarn2 instead of npm and yarn, we need to use yarn workspace in this project
- update infrastructure like: eslint, husky and so on

### CODE REVIEW

**Comment by hsluoyz** [comment]
@nodece remove

image

**Review by Zxilly — APPROVED** [review]
lgtm

**Review by hsluoyz — CHANGES_REQUESTED** [review]
Remove Merge commits:

image

**Comment by hsluoyz** [comment]
@nodece plz rebase to master HEAD locally and then send PR

**Comment by nodece** [comment]
@hsluoyz fixed

**Pull request merged**
