### PR TITLE
fix: remove async function in roleManager

### PR DESCRIPTION
**Pull request by 17bit**
Target for: https://github.com/casbin/node-casbin/issues/224

### CODE REVIEW

**Comment by hsluoyz** [comment]
@17bit please fix DCO:

image

**Comment by 17bit** [comment]
> @17bit please fix DCO:
> 
> image

fixed

**Comment by hsluoyz** [comment]
@fgblomqvist please review.

**Comment by nodece** [comment]
@hsluoyz @17bit 

I don't think it's a good idea to remove asynchronous functions from RoleManager. 
Asynchrony method is inevitable.  It's a problem we've had: https://github.com/casbin/node-casbin/issues/46.

**Comment by hsluoyz** [comment]
OK.

@17bit let's provide another new set of Sync APIs in the same role manager, function names ending with `Sync`.

**Comment by divy9881** [comment]
I agree with @nodece and @hsluoyz that we shouldn't change the async returns. Instead we can expose a different interface for sync returns as to extend our support.

Although, it is fine that we remove the async returns from following methods,
```
addMatchingFunc()
addDomainMatchingFunc()
```
as it doesn't make sense.

**Comment by fgblomqvist** [comment]
I second what has been said. Either add separate sync functions to interface/API or add a new sync interface (separate from the async one). Might be a bit awkward to have both sync and async functions in the same interface, since all async role managers will only be able to support the async methods (and I guess will throw on the sync ones perhaps).

**Comment by hsluoyz** [comment]
@fgblomqvist @nodece @divy9881 here are two ways to build the Sync API:

1. Make a new class called `RoleManagerSync`, add all Sync APIs into it.
2. Reuse the current `RoleManager` class, with both Async APIs and Sync APIs.

I slightly tend to option 2 because:

1. We can reuse the code better if the Sync and Async functions sit inside the same class.
2. Most of the functions actually never have chance to have a real "Async" behavior, like `setLogger()`, `getRoleManager()`. We can just remove `async` from them and don't need to prepare both forms for them.
3. `RoleManager` is actually similar to other classes like `Enforcer`, `Adapter`. If we don't split `Enforcer`, then we don't split `RoleManager` either.

For the function naming, we also have two options:

1. `enforce()` (for async) and `enforceSync()`, this is our current naming for async, and also the naming for Node.js core: https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/#comparing-code
2. `enforce()` (for sync) and `enforceAsync()`, our matcher evaluator: expression-eval uses this way: https://github.com/donmccurdy/expression-eval#evaluation

I slightly tend to option 2 because:

1. Most of our functions are sync, so we don't need to trail a `Sync` to most functions.
2. The bad part is that this is a API breaking change, we may need to have a major release for it.

Any comments for these two questions?

**Comment by fgblomqvist** [comment]
Ultimately I don't mind either approach. The benefit of approach 2 is that it can be done as a non-breaking change since you'd just add sync methods to the existing interface. However, at the same time, I don't necessarily see the problem with bumping the major version and making breaking changes. Any critical fixes can be backported to the previous major version for the next year or so.

Now, I'd still personally lean towards having separate classes (approach 1) since it would make the API a bit cleaner (and we wouldn't have to figure out how to best name things). As for `DefaultRoleManager`, it would just be a sync one so that would be easy to change. In case anyone wants to re-use some code from it they can inherit it and then expand/make it async where necessary.

**Comment by fgblomqvist** [comment]
I can type up a quick little example of what I had in mind a little later 🙂

**Comment by hsluoyz** [comment]
> Now, I'd still personally lean towards having separate classes (approach 1) since it would make the API a bit cleaner (and we wouldn't have to figure out how to best name things). As for DefaultRoleManager, it would just be a sync one so that would be easy to change. In case anyone wants to re-use some code from it they can inherit it and then expand/make it async where necessary.

Actually we have a lot of 3rd-party software (like adapter, middleware, etc.) developers. I'd like to hear their points about same-class or separate classes. @kibertoad @ghaiklor @willsoto @juicycleff @fospitia

Take adapter for example:

1. Same class: still `Adapter` base class, will implement `loadPolicy()` or `loadPolicyAsync()` or both. all current DB adapters (mostly likely?) will need to add trailing `Async` to their function names. "Sync"-flavor adapters like StringAdapter, JsonAdapter will remove `async` reserve word.
2. Separate class: all current DB adapters (mostly likely?) will need to move to inherit `AdapterAsync` base class, the name `Adapter` will be the base class name only for "Sync"-flavor adapters like StringAdapter, JsonAdapter.

**Comment by kibertoad** [comment]
@hsluoyz I think that having separate classes would be cleaner from implementation perspecting, and speaking from code reuse perspective, can't we have either a base class or extract shared code into stateless functions that don't rely on there being a class at all?

**Comment by kibertoad** [comment]
@hsluoyz Sounds good!

**Comment by fgblomqvist** [comment]
Agreed, sounds good to me as well!

**Comment by nodece** [comment]
> To summarize all points and keep the best compatibility, I think we can have such a solution:
> 
> ## For classes:
> 1. Separate classes: all current DB adapters (mostly likely?) will keep inheriting Adapter base class (which is for Async).
> 2. All "Sync"-flavor adapters like StringAdapter, JsonAdapter will use the new AdapterSync base class.
> 3. So most 3rd-party adapters won't need to change anything. Use shared code base class to reduce code duplicates.
> 
> ## For functions (like in Enforcer):
> 1. If it's an obvious Async-behavior API like `enforce()`, keep old API like: `enforce()` for Async and create new API like: `enforceSync()` for Sync. So no breaking change in API.
> 2. If it's actually a Sync-behavior API like `setLogger()`, `getRoleManager()`, just remove `async` keyword to make it a Sync API. But we don't trail `Sync` to its function name for simplicity.
> 
> Is this OK for you? @fgblomqvist @kibertoad

Sounds good. 

In face, we can remove the `async` from any methods, the all methods returns a type similar to `Promise<boolean> | boolean`.

Assume that all functions returns `Promise<boolean> | boolean`, when `enforceSync` is used, we have to check that any function returns `boolean`, when `enforce` is used, returns `Promise<boolean>`.

It's a way to keep the best compatibility.

**Comment by 17bit** [comment]
> > To summarize all points and keep the best compatibility, I think we can have such a solution:
> > ## For classes:
> > 
> > 1. Separate classes: all current DB adapters (mostly likely?) will keep inheriting Adapter base class (which is for Async).
> > 2. All "Sync"-flavor adapters like StringAdapter, JsonAdapter will use the new AdapterSync base class.
> > 3. So most 3rd-party adapters won't need to change anything. Use shared code base class to reduce code duplicates.
> > 
> > ## For functions (like in Enforcer):
> > 
> > 1. If it's an obvious Async-behavior API like `enforce()`, keep old API like: `enforce()` for Async and create new API like: `enforceSync()` for Sync. So no breaking change in API.
> > 2. If it's actually a Sync-behavior API like `setLogger()`, `getRoleManager()`, just remove `async` keyword to make it a Sync API. But we don't trail `Sync` to its function name for simplicity.
> > 
> > Is this OK for you? @fgblomqvist @kibertoad
> 
> Sounds good.
> 
> In face, we can remove the `async` from any methods, the all methods returns a type similar to `Promise<boolean> | boolean`.
> 
> Assume that all functions returns `Promise<boolean> | boolean`, when `enforceSync` is used, we have to check that any function returns `boolean`, when `enforce` is used, returns `Promise<boolean>`.
> 
> It's a way to keep the best compatibility.
> 
> What do you think of this? @fgblomqvist @kibertoad

That will be unable to use Async/Await and difficult to process callback.

**Comment by nodece** [comment]
@17bit If returns `promise<type`, we still can use Async/Await.

**Pull request closed without merging**
