### PR TITLE
test: add platform test

### PR DESCRIPTION
**Pull request by nodece**
Cherry-pick platform test from casbin-core.

Support:
- Angular
- React
- ~React Native~: `/home/runner/work/node-casbin/node-casbin/lib/cjs/coreEnforcer.js: Couldn't find a Program` error.

### CODE REVIEW

**Comment by nodece** [comment]
`csv-parse/sync` doesn't work.

**Comment by hsluoyz** [comment]
@nodece why do we need to add the whole projects of React, Vue and Angular into this core repo just for test? This library is the core library for Node.js (and browser) and it should be small enough.

I am not against to add CI tests for them, bu the code of whole projects of React, Vue and Angular should not be inside this repo. They can be hosted in example repos separately inside the node-casbin org (one repo for one example, also friendly for setting up example applications). The CI of this repo can pull those example code and run tests.

**Comment by nodece** [comment]
Hi @hsluoyz, 
> @nodece why do we need to add the whole projects of React, Vue and Angular examples into this core repo just for test? This library is the core library for Node.js (and browser) and it should be small enough.

Sure, just for the test.

> I am not against to add CI tests for them, but the code of whole projects of React, Vue and Angular should not be inside this repo. They can be hosted in example repos separately inside the node-casbin org (one repo for one example, also friendly for setting up example applications). The CI of this repo can pull those example code and run tests.

These files are in the test directory and will not affect anything.

**Comment by hsluoyz** [comment]
@nodece this repo should NOT contain such code for a lot of complex examples. As I said, please create new repos for holding the examples.

**Comment by nodece** [comment]
This has been moved to https://github.com/node-casbin/casbin-examples.

**Pull request closed without merging**
