### PR TITLE
improvement: convert all management_api to async function

### PR DESCRIPTION
**Pull request by nodece**
BREAKING CHANGE: 

There are affected function:

- `getPermissionsForUser()` 
- `hasPermissionForUser()` 
- `getAllSubjects()`
- `getAllNamedSubjects()`
- `getAllObjects()`
- `getAllNamedObjects()`
- `getAllActions()`
- `getAllNamedActions()`
- `getAllRoles()`
- `getAllNamedRoles()`
- `getPolicy()`
- `getFilteredPolicy()`
- `getNamedPolicy()`
- `getFilteredNamedPolicy()`
- `getGroupingPolicy()`
- `getFilteredGroupingPolicy()`
- `getNamedGroupingPolicy()`
- `getFilteredNamedGroupingPolicy()`
- `hasPolicy()`
- `hasNamedPolicy()`
- `hasGroupingPolicy()`
- `hasNamedGroupingPolicy()`
- `addFunction()`

### CODE REVIEW

**Comment by nodece** [comment]
@hsluoyz See https://github.com/casbin/node-casbin/issues/115#issuecomment-584189442 for details.

**Comment by hsluoyz** [comment]
@nodece we should release v4.0.0 after this breaking change PR.

**Comment by hsluoyz** [comment]
@nodece breaking change info is not complete here: https://github.com/casbin/node-casbin/releases/tag/v4.0.0

**Pull request merged**
